#!/bin/bash
#
echo -n "Sisesta külje a väärtus: " #väljastab teksti
read a #küsib kasutajalt väärtust
echo -n "Sisesta külje b väärtus: "
read b
#
echo sqrt "($a * $a + $b * $b)" | bc -l
echo "kolmnurga hüpotenuus on $calc"
#
# skripti lõpp
