#!/bin/bash
#
echo -n "Sisesta külje a väärtus: "
read a
echo -n "Sisesta külje b väärtus: "
read b
echo -n "Sisesta külje c väärtus: "
read c
#
#
p=`echo "scale=2; ($a+$b+$c) /2" | bc -l`
s=`echo "scale=2; ($p*($p-a)*($p-$b)*($p-$c))" | bc -l`
echo "kolmnurga pindala on"
echo $s
#
#
